name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  async_redux: ^21.3.1
  bloc: ^8.1.2
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - asset\image\bronzeMedal.png
    - asset\image\silverMedal.png
    - asset\image\profileImage.png
    - asset\image\goldMedal.png
    - asset\icons\icColor1.svg
    - asset\icons\icColor2.svg
    - asset\icons\icColor3.svg
